nimbleSizeCallNames <- c("/", "^", "*", "%%", "pow", "nimMod", "pow_int", "pmin", "pmax", 
"pairmin", "pairmax", "nimEquals", "&", "|", "==", "!=", "<=", 
">=", "<", ">", "+", "-", "abs", "cube", "nimStep", "exp", "log", 
"logit", "ilogit", "probit", "iprobit", "sqrt", "gammafn", "lgammafn", 
"log1p", "lfactorial", "factorial", "cloglog", "icloglog", "nimRound", 
"ftrunc", "ceil", "floor", "cos", "sin", "tan", "acos", "asin", 
"atan", "cosh", "sinh", "tanh", "acosh", "asinh", "atanh", "!", 
"nimIsNA", "nimIsNaN", "<-", "<<-", "=", "mean", "prod", "squaredNorm", 
"min", "max", "sum", "any", "all", "sd", "var", "det", "logdet", 
"inprod", "%*%", "t", "solve", "forwardsolve", "backsolve", "chol", 
"inverse", "nimEigen", "nimSvd", "getDerivs_wrapper", "nimDerivs_dummy", 
"nimOptim", "nimIntegrate", "nimOptimDefaultControl", "debugSizeProcessing", 
"diag", "dim", "RRtest_add", "which", "nimC", "nimRep", "nimSeqBy", 
"nimSeqLen", "nimSeqByLen", "return", "asRow", "asCol", "makeNewNimbleListObject", 
"getParam", "getBound", "nimSwitch", "[", "[[", "chainedCall", 
"nfVar", "map", ":", "if", "while", "for", "cppPointerDereference", 
"values", "(", "setSize", "resizeNoPtr", "nimArr_rcat", "nimArr_rinterval", 
"nimPrint", "nimCat", "nimDerivs", "nimDerivs_calculate", "as.integer", 
"as.numeric", "nimArrayGeneral", "setAll", "voidPtr", "run.time", 
"bessel_k", "PROTECT", "NimArr_2_SEXP", "Reval", "Rf_eval", "nimbleConvert", 
"nimbleUnconvert", "asReturnSymbol", "PDinverse_logdet", "dbinom", 
"dbinom", "dconstraint", "dnbinom", "dpois", "dbeta", "dchisq", 
"ddexp", "dexp_nimble", "dflat", "dhalfflat", "dgamma", "dinvgamma", 
"dsqrtinvgamma", "dlnorm", "dlogis", "dnorm", "dt_nonstandard", 
"dunif", "dweibull", "pbinom", "pbinom", "pnbinom", "ppois", 
"pbeta", "pchisq", "pdexp", "pexp_nimble", "pgamma", "pinvgamma", 
"plnorm", "plogis", "pnorm", "pt_nonstandard", "punif", "pweibull", 
"qbinom", "qbinom", "qnbinom", "qpois", "qbeta", "qchisq", "qdexp", 
"qexp_nimble", "qgamma", "qinvgamma", "qlnorm", "qlogis", "qnorm", 
"qt_nonstandard", "qunif", "qweibull", "rbinom", "rbinom", "rconstraint", 
"rnbinom", "rpois", "rbeta", "rchisq", "rdexp", "rexp_nimble", 
"rflat", "rhalfflat", "rgamma", "rinvgamma", "rsqrtinvgamma", 
"rlnorm", "rlogis", "rnorm", "rt_nonstandard", "runif", "rweibull", 
"dcat", "dinterval", "dcar_normal", "dcar_proper", "ddirch", 
"dmnorm_chol", "dmnorm_inv_ld", "dmulti", "dmvt_chol", "dlkj_corr_cholesky", 
"dwish_chol", "dinvwish_chol", "rcat", "rinterval", "rcar_normal", 
"rcar_proper", "rdirch", "rmnorm_chol", "rmnorm_inv_ld", "rmulti", 
"rmvt_chol", "rlkj_corr_cholesky", "rwish_chol", "rinvwish_chol", 
"dt", "qt", "pt", "rt", "dexp", "qexp", "pexp", "rexp", "nimAnyNA", 
"nimAnyNaN", "nimArr_dmnorm_chol", "nimArr_dmnorm_inv_ld", "nimArr_dmvt_chol", 
"nimArr_dlkj_corr_cholesky", "nimArr_dwish_chol", "nimArr_dinvwish_chol", 
"nimArr_dcar_normal", "nimArr_dcar_proper", "nimArr_dmulti", 
"nimArr_dcat", "nimArr_dinterval", "nimArr_ddirch", "nimArr_rmnorm_chol", 
"nimArr_rmnorm_inv_ld", "nimArr_rmvt_chol", "nimArr_rlkj_corr_cholesky", 
"nimArr_rwish_chol", "nimArr_rinvwish_chol", "nimArr_rcar_normal", 
"nimArr_rcar_proper", "nimArr_rmulti", "nimArr_rdirch", "decide", 
"checkLogProb", "checkLogProbWarn", "size", "getsize", "getNodeFunctionIndexedInfo", 
"endNimbleTimer", "calculate", "calculateDiff", "getLogProb", 
"simulate", "blank", "nfMethod", "getPtr", "startNimbleTimer", 
"passByMap", "ADbreak")
